# Generated by Django 5.1.7 on 2025-04-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_banner_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="fabric",
            field=models.CharField(blank=True, max_length=255, verbose_name="Ткань"),
        ),
        migrations.AddField(
            model_name="product",
            name="season",
            field=models.CharField(blank=True, max_length=100, verbose_name="Сезон"),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.CharField(
                blank=True,
                help_text="Например: 42/44/46/48",
                max_length=100,
                verbose_name="Размеры",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/multi/", verbose_name="Фото"),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt-текст"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="backend.product",
                    ),
                ),
            ],
        ),
    ]
