# Generated by Django 5.1.7 on 2025-04-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_product_fabric_product_season_product_sizes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Главное фото"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=models.CharField(blank=True, max_length=100, verbose_name="Размеры"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/", verbose_name="Фото"),
        ),
    ]
