# Generated by Django 5.1.7 on 2025-05-07 16:41

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_alter_product_options_remove_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="thumbnail",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="products/thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
