# Generated by Django 5.1.7 on 2025-05-20 13:53

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_remove_productimage_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="thumbnail",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="products/thumbnails/"
            ),
        ),
    ]
