services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/static
      - ./backend/media:/app/media
    networks:
      - webnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static:ro
      - ./backend/media:/app/media:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    networks:
      - webnet

volumes:
  pgdata:
  static_volume:

networks:
  webnet:
