# Generated by Django 5.1.7 on 2025-05-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_productimage_thumbnail_alter_productimage_alt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="thumbnail",
        ),
    ]
