# Generated by Django 5.1.7 on 2025-05-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_productimage_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="thumbnail",
        ),
    ]
