# Generated by Django 5.1.7 on 2025-07-10 06:48
from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Product = apps.get_model('backend', 'Product')
    for p in Product.objects.filter(slug=''):
        p.slug = slugify(p.name)
        p.save()

    Category = apps.get_model('backend', 'Category')
    for c in Category.objects.filter(slug=''):
        c.slug = slugify(c.name)
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_productimage_thumbnail'),
    ]

    operations = [
        migrations.RunPython(
            populate_slugs,
            reverse_code=migrations.RunPython.noop
        ),
    ]
